### ISSUE TITLE
AttributeError: 'function' object has no attribute 'Variable'

### ISSUE THREAD

**Issue by liu-x-p** [andi611/ZeroSpeech-TTS-without-T#5]
Hi, thanks for sharing your code. 
When I run the step2 in training, with the commmand `python3 main.py --train_p --load_model --load_train_model_name=model.pth-ae-400000`
it will give the error report
**AttributeError: 'function' object has no attribute 'Variable'**
How can I solve this problem?

**Comment by andi611** [comment]
Hi, can you provide the full error log?
I speculate this error is caused by a different Pytorch version.

**Comment by liu-x-p** [comment]
@andi611  
Thank you.
The error report is 
```
Traceback (most recent call last):.20, gp=407.61, loss_clf=0.71, acc=0.50
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 157, in main
    trainer.train(model_path, args.flag, mode='patchGAN', target_guided=args.train_tgat)		# Stage 2 training
  File "/home/omnisky/mount/zero/ZeroSpeech-TTS-without-T/trainer.py", line 509, in train
    self.logger.scalar_summary(tag, value, iteration + 1)
  File "/home/omnisky/mount/zero/ZeroSpeech-TTS-without-T/utils.py", line 85, in scalar_summary
    self.writer.add_scalar(tag, value, step)
  File "/home/omnisky/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 272, in add_scalar
    self.file_writer.add_summary(scalar(tag, scalar_value), global_step)
  File "/home/omnisky/anaconda3/lib/python3.6/site-packages/tensorboardX/summary.py", line 86, in scalar
    scalar = makenp(scalar)
  File "/home/omnisky/anaconda3/lib/python3.6/site-packages/tensorboardX/x2num.py", line 15, in makenp
    return pytorch_np(x, modality)
  File "/home/omnisky/anaconda3/lib/python3.6/site-packages/tensorboardX/x2num.py", line 24, in pytorch_np
    if isinstance(x, torch.autograd.variable.Variable):
AttributeError: 'function' object has no attribute 'Variable'
```

**Comment by liu-x-p** [comment]
I used torch1.4 and have that problem. I try to run it on torch0.41, and it works now.
Thank you!
