### ISSUE TITLE
AttributeError: cffi library '...\Library\bin\sndfile.dll' has no function, constant or global variable named 'sf_wchar_open'

### ISSUE THREAD

**Issue by ZhengRachel** [andi611/ZeroSpeech-TTS-without-T#6]
Hi~thanks for sharing your code!
I am trying to run the code but I encounter the following error:
Traceback (most recent call last):
  File "main.py", line 209, in <module> main()
  File "main.py", line 126, in main remake=args.remake)
  File "F:\TTSwithoutT\ZeroSpeech-TTS-without-T\preprocess.py", line 43, in preprocess
    make_dataset(grps, seg_len, root_dir=source_path)
  File "F:\TTSwithoutT\ZeroSpeech-TTS-without-T\preprocess.py", line 93, in make_dataset
    mel_spec, lin_spec = get_spectrograms(filename)
  File "F:\TTSwithoutT\ZeroSpeech-TTS-without-T\preprocess.py", line 230, in get_spectrograms
    y, sr = librosa.load(sound_file, sr=hp.sr) # Loading sound file
  File "D:\Anaconda\envs\TTSnoT\lib\site-packages\librosa\core\audio.py", line 146, in load
    with sf.SoundFile(path) as sf_desc:
  File "D:\Anaconda\envs\TTSnoT\lib\site-packages\soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\Anaconda\envs\TTSnoT\lib\site-packages\soundfile.py", line 1170, in _open
    openfunction = _snd.sf_wchar_open
AttributeError: cffi library 'D:\Anaconda\envs\TTSnoT\Library\bin\sndfile.dll' has no function, constant or global variable named 'sf_wchar_open'
I wonder how i can fix it.Does it has something to do with the system or the pakage release version?(I am on windows OS, python 3.7.7, librosa0.8.0) 
Looking forward to your reply.

**Comment by andi611** [comment]
Hi,

This code can be run on any platform.

According to this: https://github.com/bastibe/SoundFile/issues/253
I believe the error you have is because your soundfile is installed with conda, 
and the conda version is broken.
You can try to install with: `pip install soundfile`

I hope this helps.

**Comment by ZhengRachel** [comment]
Yes! Thank you!
